# Generated by Django 3.1.5 on 2021-01-13 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='first_year_images/')),
                ('desc', models.TextField(blank=True, null=True)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ForthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='forth_year_images/')),
                ('desc', models.TextField(blank=True, null=True)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SecondYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='second_year_images/')),
                ('desc', models.TextField(blank=True, null=True)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='third_year_images/')),
                ('desc', models.TextField(blank=True, null=True)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BuyConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='اكتب اسمك بالكامل')),
                ('receiptnumber', models.CharField(max_length=1000, verbose_name='اكتب رقم إيصال الدفع')),
                ('gmailaccount', models.EmailField(max_length=254, verbose_name='اكتب الچيميل الخاص بجوجل درايڤ')),
                ('Paid_NotPaid', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 13, 17, 25, 26, 552555))),
                ('firstyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.firstyear')),
                ('forthyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.forthyear')),
                ('secondyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.secondyear')),
                ('thirdyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.thirdyear')),
            ],
        ),
    ]
