# Generated by Django 3.1.5 on 2021-01-14 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210114_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyconfirmation',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 14, 15, 28, 52, 901279)),
        ),
    ]
