# Generated by Django 3.1.5 on 2021-01-20 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210114_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyconfirmation',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 20, 17, 35, 53, 556759)),
        ),
    ]
